version: 2.1
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - docker build -f Dockerfile.dev -t app-testing .
      - docker run -e="CI=true" app-testing npm run test
