version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t react-app-build:1.0.0 .
      - run: docker run react-app-build:1.0.0
      - run: ls

workflows:
  my-custom-workflow:
    jobs:
      - build_and_deploy
