version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build_and_test:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f Dockerfile.dev -t app-testing .
      - run: docker run -e="CI=true" app-testing npm run test

workflows:
  my-custom-workflow:
    jobs:
      - build_and_test
